 const famosos = [
  { nombre: "Sebastián Abreu", foto: "img/abreu.jpg" },
  { nombre: "Diego Lugano", foto: "img/lugano.jpg" },
  { nombre: "Mauro Icardi", foto: "img/mauro_icardi.jpg" },
  { nombre: "Nicolás de la Cruz", foto: "img/nicolas_de_la_cruz.jpg" },
  { nombre: "Luis Suárez", foto: "img/luis_suarez.jpg" },
  { nombre: "Lionel Messi", foto: "img/lionel_messi.jpg" },
  { nombre: "Diego Forlán", foto: "img/diego_forlan.jpg" },
  { nombre: "Cristiano Ronaldo", foto: "img/cristiano_ronaldo.jpg" },
  { nombre: "Keylor Navas", foto: "img/keylor_navas.jpg" },
  { nombre: "Manuel Neuer", foto: "img/manuel_neuer.jpg" },
  { nombre: "Martín Palermo", foto: "img/martin_palermo.jpg" },
  { nombre: "Luciano Boggio", foto: "img/boggio.jpg" },
  { nombre: "Nico López", foto: "img/nico_lopez.jpg" },
  { nombre: "Gonzalo Petit", foto: "img/petit.jpg" },
  { nombre: "Eduardo Vargas", foto: "img/eduardo_vargas.jpg" },
  { nombre: "Gonzalo Carneiro", foto: "img/carneiro.jpg" },
  { nombre: "Luis Mejía", foto: "img/mejia.jpg" },
  { nombre: "Diego Maradona", foto: "img/diego_maradona.jpg" },
  { nombre: "Pelé", foto: "img/pele.jpg" },
  { nombre: "Gabriel Batistuta", foto: "img/gabriel_batistuta.jpg" },
  { nombre: "Andrés Iniesta", foto: "img/andres_iniesta.jpg" },
  { nombre: "Sergio Agüero", foto: "img/sergio_aguero.jpg" },
  { nombre: "Fernando Muslera", foto: "img/fernando_muslera.jpg" },
  { nombre: "Carlos Tévez", foto: "img/carlos_tevez.jpg" },
  { nombre: "Javier Mascherano", foto: "img/javier_mascherano.jpg" },
  { nombre: "Juan Román Riquelme", foto: "img/juan_roman_riquelme.jpg" },
  { nombre: "Fede Valverde", foto: "img/fede_valverde.jpg" },
  { nombre: "Paulo Dybala", foto: "img/paulo_dybala.jpg" },
  { nombre: "Ángel Di María", foto: "img/angel_di_maria.jpg" },
  { nombre: "Alfonso Espino", foto: "img/alfonso_espino.jpg" },
  { nombre: "Rodrigo Bentancur", foto: "img/rodrigo_bentancur.jpg" },
  { nombre: "Facundo Pellistri", foto: "img/facundo_pellistri.jpg" },
  { nombre: "Kylian Mbappé", foto: "img/kylian_mbappe.jpg" },
  { nombre: "Neymar Jr.", foto: "img/neymar_jr.jpg" },
  { nombre: "Erling Haaland", foto: "img/erling_haaland.jpg" },
  { nombre: "Robert Lewandowski", foto: "img/robert_lewandowski.jpg" },
  { nombre: "Cole Palmer", foto: "img/colepalmer.jpg" },
  { nombre: "Luka Modrić", foto: "img/luka_modric.jpg" },
  { nombre: "Toni Kroos", foto: "img/toni_kroos.jpg" },
  { nombre: "Mohamed Salah", foto: "img/mohamed_salah.jpg" },
  { nombre: "Virgil van Dijk", foto: "img/virgil_van_dijk.jpg" },
  { nombre: "Kevin De Bruyne", foto: "img/kevin_de_bruyne.jpg" },
  { nombre: "Harry Kane", foto: "img/harry_kane.jpg" },
  { nombre: "Antoine Griezmann", foto: "img/antoine_griezmann.jpg" },
  { nombre: "Gerard Piqué", foto: "img/gerard_pique.jpg" },
  { nombre: "Sergio Ramos", foto: "img/sergio_ramos.jpg" },
  { nombre: "Marcelo", foto: "img/marcelo.jpg" },
  { nombre: "Gianluigi Buffon", foto: "img/gianluigi_buffon.jpg" },
  { nombre: "Iker Casillas", foto: "img/iker_casillas.jpg" },
  { nombre: "Francesco Totti", foto: "img/francesco_totti.jpg" },
  { nombre: "Ronaldinho", foto: "img/ronaldinho.jpg" },
  { nombre: "Ivan Alonso", foto: "img/ivanalonso.jpg" },
  { nombre: "Edinson Cavani", foto: "img/edinson_cavani.jpg" },
  { nombre: "Darwin Núñez", foto: "img/darwin_nunez.jpg" },
  { nombre: "Sebastián Coates", foto: "img/sebastian_coates.jpg" },
  { nombre: "Martín Cáceres", foto: "img/martin_caceres.jpg" },
  { nombre: "Diego Godín", foto: "img/diego_godin.jpg" },
  { nombre: "Óscar Tabárez", foto: "img/oscar_tabarez.jpg" },
  { nombre: "Álvaro Recoba", foto: "img/alvaro_recoba.jpg" },
  { nombre: "Rubén Sosa", foto: "img/ruben_sosa.jpg" },
  { nombre: "Enzo Francescoli", foto: "img/enzo_francescoli.jpg" },
  { nombre: "Lucas Torreira", foto: "img/lucas_torreira.jpg" },
  { nombre: "Jonathan Rodríguez", foto: "img/jonathan_rodriguez.jpg" },
  { nombre: "Agustín Canobbio", foto: "img/agustin_canobbio.jpg" },
  { nombre: "Brian Rodríguez", foto: "img/brian_rodriguez.jpg" },
  { nombre: "Brian Ocampo", foto: "img/braianocampo.jpg" },
  { nombre: "Jeremia Recoba", foto: "img/recoba_jr.jpg" },
  { nombre: "Diego Simeone", foto: "img/simeone.jpg" },
  { nombre: "José Mourinho", foto: "img/mourinho.jpg" },
  { nombre: "Pep Guardiola", foto: "img/guardiola.jpg" },
  { nombre: "Carlo Ancelotti", foto: "img/ancelotti.jpg" },
  { nombre: "Zinedine Zidane", foto: "img/zidane.jpg" },
  { nombre: "Gonzalo Bergessio", foto: "img/gonzalo_bergessio.jpg" },
  { nombre: "Nicolas Lodeiro", foto: "img/nico_lodeiro.jpg" },
  { nombre: "Luis Artime", foto: "img/luis_artime.jpg" },
  { nombre: "Héctor Scarone", foto: "img/scarone.jpg" },
  { nombre: "Atilio García", foto: "img/atilio_garcia.jpg" },
  { nombre: "Felipe Carballo", foto: "img/felipe_carballo.jpg" },
  { nombre: "Matías Viña", foto: "img/matias_vina.jpg" },
  { nombre: "Felipe Carvalho", foto: "img/felipe_carvalho.jpg" },
  { nombre: "Guillermo Cotugno", foto: "img/guillermo_cotugno.jpg" },
  { nombre: "Ignacio Lores", foto: "img/ignacio_lores.jpg" },
  { nombre: "Franco Fagúndez", foto: "img/franco_fagundez.jpg" },
  { nombre: "Facundo Machado", foto: "img/facundo_machado.jpg" },
  { nombre: "Yonatan Rodríguez", foto: "img/yonatan_rodriguez.jpg" },
  { nombre: "Christian Oliva", foto: "img/christian_oliva.jpg" },
  { nombre: "Sergio Rochet", foto: "img/sergio_rochet.jpg" },
  { nombre: "Emiliano Velázquez", foto: "img/emiliano_velazquez.jpg" },
  { nombre: "Gabriel Báez", foto: "img/gabriel_baez.jpg" },
  { nombre: "Paolo Calione", foto: "img/paolo_calione.jpg" },
  { nombre: "Lucas Villalba", foto: "img/lucas_villalba.jpg" },
  { nombre: "Exequiel Mereles", foto: "img/exequiel_mereles.jpg" },
  { nombre: "Bruno Arady", foto: "img/bruno_arady.jpg" },
  { nombre: "Brayan Cortés", foto: "img/brayan_cortes.jpg" },
  { nombre: "Gastón Silva", foto: "img/gaston_silva.jpg" },
  { nombre: "Damián Suárez", foto: "img/damian_suarez.jpg" },
  { nombre: "Emanuel Gularte", foto: "img/emanuel_gularte.jpg" },
  { nombre: "Maximiliano Olivera", foto: "img/maximiliano_olivera.jpg" },
  { nombre: "Léo Coelho", foto: "img/leo_coelho.jpg" },
  { nombre: "Pedro Milans", foto: "img/pedro_milans.jpg" },
  { nombre: "Ignacio Sosa", foto: "img/ignacio_sosa.jpg" },
  { nombre: "Leonardo Fernández", foto: "img/leonardo_fernandez.jpg" },
  { nombre: "Eduardo Darias", foto: "img/eduardo_darias.jpg" },
  { nombre: "Jesús Trindade", foto: "img/jesus_trindade.jpg" },
  { nombre: "Eric Remedi", foto: "img/eric_remedi.jpg" },
  { nombre: "David Terans", foto: "img/david_terans.jpg" },
  { nombre: "Javier Cabrera", foto: "img/javier_cabrera.jpg" },
  { nombre: "Héctor Villalba", foto: "img/hector_villalba.jpg" },
  { nombre: "Maximiliano Silvera", foto: "img/maximiliano_silvera.jpg" },
  { nombre: "Matías Arezo", foto: "img/matias_arezo.jpg" },
  { nombre: "Fernando Morena", foto: "img/fernando_morena.jpg" },
  { nombre: "Obdulio Varela", foto: "img/obdulio_varela.jpg" },
{ nombre: "Ronaldo Nazario", foto: "img/ronaldo.jpg" },
{ nombre: "Alessandro Del Piero", foto: "img/delpiero.jpg" },
{ nombre: "Andrea Pirlo", foto: "img/pirlo.jpg" },
{ nombre: "Ángel Correa", foto: "img/correa.jpg" },
{ nombre: "Arjen Robben", foto: "img/robben.jpg" },
{ nombre: "Ashley Cole", foto: "img/ashleycole.jpg" },
{ nombre: "Blaise Matuidi", foto: "img/matuidi.jpg" },
{ nombre: "Cesc Fàbregas", foto: "img/fabregas.jpg" },
{ nombre: "Dani Alves", foto: "img/danialves.jpg" },
{ nombre: "David Beckham", foto: "img/beckham.jpg" },
{ nombre: "David Silva", foto: "img/silva.jpg" },
{ nombre: "Diego Costa", foto: "img/diegocosta.jpg" },
{ nombre: "Edin Džeko", foto: "img/dzeko.jpg" },
{ nombre: "Fernando Torres", foto: "img/torres.jpg" },
{ nombre: "Franck Ribéry", foto: "img/ribery.jpg" },
{ nombre: "Gareth Bale", foto: "img/bale.jpg" },
{ nombre: "Gerard Moreno", foto: "img/gerardmoreno.jpg" },
{ nombre: "Gianluigi Donnarumma", foto: "img/donnarumma.jpg" },
{ nombre: "Giorgio Chiellini", foto: "img/chiellini.jpg" },
{ nombre: "Guti", foto: "img/guti.jpg" },
{ nombre: "Iago Aspas", foto: "img/aspas.jpg" },
{ nombre: "James Rodríguez", foto: "img/james.jpg" },
{ nombre: "Javier Hernández", foto: "img/chicharito.jpg" },
{ nombre: "João Félix", foto: "img/joaofelix.jpg" },
{ nombre: "Juan Mata", foto: "img/mata.jpg" },
{ nombre: "Karim Benzema", foto: "img/benzema.jpg" },
{ nombre: "Kevin-Prince Boateng", foto: "img/boateng.jpg" },
{ nombre: "Luka Jović", foto: "img/jovic.jpg" },
{ nombre: "Marcelo Brozović", foto: "img/brozovic.jpg" },
{ nombre: "Marco Reus", foto: "img/reus.jpg" },
{ nombre: "Mario Götze", foto: "img/gotze.jpg" },
{ nombre: "Mario Mandžukić", foto: "img/mandzukic.jpg" },
{ nombre: "Mats Hummels", foto: "img/hummels.jpg" },
{ nombre: "Memphis Depay", foto: "img/depay.jpg" },
{ nombre: "Michy Batshuayi", foto: "img/batshuayi.jpg" },
{ nombre: "Raheem Sterling", foto: "img/sterling.jpg" },
{ nombre: "Raúl González", foto: "img/raul.jpg" },
{ nombre: "Robert Pires", foto: "img/pires.jpg" },
{ nombre: "Romelu Lukaku", foto: "img/lukaku.jpg" },
{ nombre: "Samuel Eto’o", foto: "img/etoo.jpg" },
{ nombre: "Franco Mastantuono", foto: "img/franco_mastantuono.jpg" },
{ nombre: "Jude Bellingham", foto: "img/jude_bellingham.jpg" },
{ nombre: "Vinícius Júnior", foto: "img/vinicius_junior.jpg" },
{ nombre: "Lamine Yamal", foto: "img/lamine_yamal.jpg" },
{ nombre: "Pedri", foto: "img/pedri.jpg" },
{ nombre: "Jamal Musiala", foto: "img/jamal_musiala.jpg" },
{ nombre: "Florian Wirtz", foto: "img/florian_wirtz.jpg" },
{ nombre: "Bukayo Saka", foto: "img/bukayo_saka.jpg" },
{ nombre: "Phil Foden", foto: "img/phil_foden.jpg" },
{ nombre: "Declan Rice", foto: "img/declan_rice.jpg" },
{ nombre: "Trent Alexander-Arnold", foto: "img/trent_alexander_arnold.jpg" },
{ nombre: "Marcus Rashford", foto: "img/marcus_rashford.jpg" },
{ nombre: "Mason Mount", foto: "img/mason_mount.jpg" },
{ nombre: "Kai Havertz", foto: "img/kai_havertz.jpg" },
{ nombre: "Joshua Kimmich", foto: "img/joshua_kimmich.jpg" },
{ nombre: "Leon Goretzka", foto: "img/leon_goretzka.jpg" },
{ nombre: "Alphonso Davies", foto: "img/alphonso_davies.jpg" },
{ nombre: "Theo Hernández", foto: "img/theo_hernandez.jpg" },
{ nombre: "Rafael Leão", foto: "img/rafael_leao.jpg" },
{ nombre: "Khvicha Kvaratskhelia", foto: "img/khvicha_kvaratskhelia.jpg" },
{ nombre: "Lautaro Martínez", foto: "img/lautaro_martinez.jpg" },
{ nombre: "Joško Gvardiol", foto: "img/josko_gvardiol.jpg" },
{ nombre: "Achraf Hakimi", foto: "img/achraf_hakimi.jpg" },
{ nombre: "Heung-min Son", foto: "img/son_heung_min.jpg" },
{ nombre: "Bruno Fernandes", foto: "img/bruno_fernandes.jpg" },
{ nombre: "Casemiro", foto: "img/casemiro.jpg" },
{ nombre: "Antony", foto: "img/antony.jpg" },
{ nombre: "Richarlison", foto: "img/richarlison.jpg" },
{ nombre: "Álisson Becker", foto: "img/alisson_becker.jpg" },
{ nombre: "Thibaut Courtois", foto: "img/thibaut_courtois.jpg" },
{ nombre: "Jan Oblak", foto: "img/jan_oblak.jpg" },
{ nombre: "Raphaël Varane", foto: "img/raphael_varane.jpg" },
{ nombre: "Antonio Rüdiger", foto: "img/antonio_rudiger.jpg" },
{ nombre: "Áymeric Laporte", foto: "img/aymeric_laporte.jpg" },
{ nombre: "João Cancelo", foto: "img/joao_cancelo.jpg" },
{ nombre: "Bernardo Silva", foto: "img/bernardo_silva.jpg" },
{ nombre: "Riyad Mahrez", foto: "img/riyad_mahrez.jpg" },
{ nombre: "Martin Ødegaard", foto: "img/martin_odegaard.jpg" },
{ nombre: "Christian Pulisic", foto: "img/christian_pulisic.jpg" },
{ nombre: "Xavi Simons", foto: "img/xavi_simons.jpg" },
{ nombre: "Federico Chiesa", foto: "img/federico_chiesa.jpg" },
];
// =========================================================
// INSERCIÓN AL FINAL DE famosos.js
// Esto permite que el servidor de Node.js pueda importar la lista
// =========================================================
module.exports = { famosos };

window.famosos = famosos;
