 const famosos = [
  { nombre: "Aaron Mooy", foto: "img/aaron_mooy.jpg" },
  { nombre: "Aaron Ramsey", foto: "img/aaron_ramsey.jpg" },
  { nombre: "Aaron Ramsdale", foto: "img/aaron_ramsdale.jpg" },
  { nombre: "Abedi Pelé", foto: "img/abedi_pele.jpg" },
  { nombre: "Achraf Hakimi", foto: "img/achraf_hakimi.jpg" },
  { nombre: "Adriano", foto: "img/adriano.jpg" },
  { nombre: "Agustín Canobbio", foto: "img/agustin_canobbio.jpg" },
  { nombre: "Agustín Delgado", foto: "img/agustin_delgado.jpg" },
  { nombre: "Ander Herrera", foto: "img/ander_herrera.jpg" },
  { nombre: "Andre Schürrle", foto: "img/andre_schurrle.jpg" },
  { nombre: "Andrea Barzagli", foto: "img/andrea_barzagli.jpg" },
  { nombre: "Andrea Belotti", foto: "img/andrea_belotti.jpg" },
  { nombre: "Andrea Pirlo", foto: "img/andrea_pirlo.jpg" },
  { nombre: "Andreas Christensen", foto: "img/andreas_christensen.jpg" },
  { nombre: "Andreas Pereira", foto: "img/andreas_pereira.jpg" },
  { nombre: "Andrej Kramarić", foto: "img/andrej_kramaríc.jpg" },
  { nombre: "Andrés Guardado", foto: "img/andres_guardado.jpg" },
  { nombre: "Andrés Iniesta", foto: "img/andres_iniesta.jpg" },
  { nombre: "Andy Robertson", foto: "img/andy_robertson.jpg" },
  { nombre: "Ángel Correa", foto: "img/angel_correa.jpg" },
  { nombre: "Ángel Di María", foto: "img/angel_di_maría.jpg" },
  { nombre: "Angelo Peruzzi", foto: "img/angelo_peruzzi.jpg" },
  { nombre: "Ansu Fati", foto: "img/ansu_fati.jpg" },
  { nombre: "Anthony Martial", foto: "img/anthony_martial.jpg" },
  { nombre: "Antonio Cassano", foto: "img/antonio_cassano.jpg" },
  { nombre: "Antonio Di Natale", foto: "img/antonio_di_natale.jpg" },
  { nombre: "Antonio Rüdiger", foto: "img/antonio_rúdiger.jpg" },
  { nombre: "Antonio Valencia", foto: "img/antonio_valencia.jpg" },
  { nombre: "Antoine Griezmann", foto: "img/antoine_griezmann.jpg" },
  { nombre: "Antony", foto: "img/antony.jpg" },
  { nombre: "Álvaro Arbeloa", foto: "img/alvaro_arbeloa.jpg" },
  { nombre: "Álvaro Morata", foto: "img/alvaro_morata.jpg" },
  { nombre: "Álvaro Recoba", foto: "img/alvaro_recoba.jpg" },
  { nombre: "Ariel Ortega", foto: "img/ariel_ortega.jpg" },
  { nombre: "Aritz Aduriz", foto: "img/aritz_aduriz.jpg" },
  { nombre: "Arjen Robben", foto: "img/arjen_robben.jpg" },
  { nombre: "Arrigo Sacchi", foto: "img/arrigo_sacchi.jpg" },
  { nombre: "Arturo Vidal", foto: "img/arturo_vidal.jpg" },
  { nombre: "Ashley Cole", foto: "img/ashley_cole.jpg" },
  { nombre: "Atilio García", foto: "img/atilio_garcía.jpg" },
  { nombre: "Aurelien Tchouameni", foto: "img/aurelien_tchouameni.jpg" },
  { nombre: "Axel Witsel", foto: "img/axel_witsel.jpg" },
  { nombre: "Aymeric Laporte", foto: "img/aymeric_laporte.jpg" },
  { nombre: "Azzedine Ounahi", foto: "img/azzedine_ounahi.jpg" },
  { nombre: "Badr El Kaddouri", foto: "img/badr_el_kaddouri.jpg" },
  { nombre: "Bastian Schweinsteiger", foto: "img/bastian_schweinsteiger.jpg" },
  { nombre: "Bebeto", foto: "img/bebeto.jpg" },
  { nombre: "Ben Chilwell", foto: "img/ben_chilwell.jpg" },
  { nombre: "Benedikt Höwedes", foto: "img/benedikt_howedes.jpg" },
  { nombre: "Benjamin Pavard", foto: "img/benjamin_pavard.jpg" },
  { nombre: "Benni McCarthy", foto: "img/benni_mccarthy.jpg" },
  { nombre: "Bernd Leno", foto: "img/bernd_leno.jpg" },
  { nombre: "Bernardo Silva", foto: "img/bernardo_silva.jpg" },
  { nombre: "Blaise Matuidi", foto: "img/blaise_matuidi.jpg" },
  { nombre: "Bobby Charlton", foto: "img/bobby_charlton.jpg" },
  { nombre: "Borja Iglesias", foto: "img/borja_iglesias.jpg" },
  { nombre: "Brad Friedel", foto: "img/brad_friedel.jpg" },
  { nombre: "Breel Embolo", foto: "img/breel_embolo.jpg" },
  { nombre: "Bremer", foto: "img/bremer.jpg" },
  { nombre: "Brian Ocampo", foto: "img/brian_ocampo.jpg" },
  { nombre: "Brian Rodríguez", foto: "img/brian_rodríguez.jpg" },
  { nombre: "Bruno Arady", foto: "img/bruno_arady.jpg" },
  { nombre: "Bruno Fernandes", foto: "img/bruno_fernandes.jpg" },
  { nombre: "Bruno Guimarães", foto: "img/bruno_guimaríes.jpg" },
  { nombre: "Bukayo Saka", foto: "img/bukayo_saka.jpg" },
  { nombre: "Cafu", foto: "img/cafu.jpg" },
  { nombre: "Carlos 'El Pibe' Valderrama", foto: "img/carlos_el_pibe_valderrama.jpg" },
  { nombre: "Carlos Alberto Torres", foto: "img/carlos_alberto_torres.jpg" },
  { nombre: "Carlos Gamarra", foto: "img/carlos_gamarra.jpg" },
  { nombre: "Carlos Tévez", foto: "img/carlos_tévez.jpg" },
  { nombre: "Carlo Ancelotti", foto: "img/carlo_ancelotti.jpg" },
  { nombre: "Carles Puyol", foto: "img/carles_puyol.jpg" },
  { nombre: "Casemiro", foto: "img/casemiro.jpg" },
  { nombre: "Cesc Fàbregas", foto: "img/cesc_fábregas.jpg" },
  { nombre: "César Azpilicueta", foto: "img/cesar_azpilicueta.jpg" },
  { nombre: "Cho Gue-sung", foto: "img/cho_gue_sung.jpg" },
  { nombre: "Christian Cueva", foto: "img/christian_cueva.jpg" },
  { nombre: "Christian Eriksen", foto: "img/christian_eriksen.jpg" },
  { nombre: "Christian Oliva", foto: "img/christian_oliva.jpg" },
  { nombre: "Christian Pulisic", foto: "img/christian_pulisic.jpg" },
  { nombre: "Christian Vieri", foto: "img/christian_vieri.jpg" },
  { nombre: "Christoph Kramer", foto: "img/christoph_kramer.jpg" },
  { nombre: "Clarence Seedorf", foto: "img/clarence_seedorf.jpg" },
  { nombre: "Claudio Bravo", foto: "img/claudio_bravo.jpg" },
  { nombre: "Claudio Caniggia", foto: "img/claudio_caniggia.jpg" },
  { nombre: "Claudio Marchisio", foto: "img/claudio_marchisio.jpg" },
  { nombre: "Claudio Pizarro", foto: "img/claudio_pizarro.jpg" },
  { nombre: "Clint Dempsey", foto: "img/clint_dempsey.jpg" },
  { nombre: "Cole Palmer", foto: "img/cole_palmer.jpg" },
  { nombre: "Corentin Tolisso", foto: "img/corentin_tolisso.jpg" },
  { nombre: "Cristian 'Cuti' Romero", foto: "img/cristian_cuti_romero.jpg" },
  { nombre: "Cristiano Ronaldo", foto: "img/cristiano_ronaldo.jpg" },
  { nombre: "Cuauhtémoc Blanco", foto: "img/cuauhtemoc_blanco.jpg" },
  { nombre: "Damián Suárez", foto: "img/damían_suárez.jpg" },
  { nombre: "DaMarcus Beasley", foto: "img/damarcus_beasley.jpg" },
  { nombre: "Dani Alves", foto: "img/dani_alves.jpg" },
  { nombre: "Dani Carvajal", foto: "img/dani_carvajal.jpg" },
  { nombre: "Dani Olmo", foto: "img/dani_olmo.jpg" },
  { nombre: "Daniel Passarella", foto: "img/daniel_passarella.jpg" },
  { nombre: "Daniele De Rossi", foto: "img/daniele_de_rossi.jpg" },
  { nombre: "Danilo Pereira", foto: "img/danilo_pereira.jpg" },
  { nombre: "Darwin Núñez", foto: "img/darwin_núñez.jpg" },
  { nombre: "David Alaba", foto: "img/david_alaba.jpg" },
  { nombre: "David Beckham", foto: "img/david_beckham.jpg" },
  { nombre: "David de Gea", foto: "img/david_de_gea.jpg" },
  { nombre: "David Luiz", foto: "img/david_luiz.jpg" },
  { nombre: "David Silva", foto: "img/david_silva.jpg" },
  { nombre: "David Terans", foto: "img/david_terans.jpg" },
  { nombre: "David Trezeguet", foto: "img/david_trezeguet.jpg" },
  { nombre: "David Villa", foto: "img/david_villa.jpg" },
  { nombre: "Davide Calabria", foto: "img/davide_calabria.jpg" },
  { nombre: "Davor Šuker", foto: "img/davor_šuker.jpg" },
  { nombre: "Dejan Savićević", foto: "img/dejan_savićević.jpg" },
  { nombre: "Declan Rice", foto: "img/declan_rice.jpg" },
  { nombre: "Demetrio Albertini", foto: "img/demetrio_albertini.jpg" },
  { nombre: "Denilson", foto: "img/denilson.jpg" },
  { nombre: "Dennis Bergkamp", foto: "img/dennis_bergkamp.jpg" },
  { nombre: "Denzel Dumfries", foto: "img/denzel_dumfries.jpg" },
  { nombre: "Didier Deschamps", foto: "img/didier_deschamps.jpg" },
  { nombre: "Didier Drogba", foto: "img/didier_drogba.jpg" },
  { nombre: "Diego Forlán", foto: "img/diego_forlán.jpg" },
  { nombre: "Diego Godín", foto: "img/diego_godín.jpg" },
  { nombre: "Diego Lugano", foto: "img/diego_lugano.jpg" },
  { nombre: "Diego Maradona", foto: "img/diego_maradona.jpg" },
  { nombre: "Diego Simeone", foto: "img/diego_simeone.jpg" },
  { nombre: "Dida", foto: "img/dida.jpg" },
  { nombre: "Dino Zoff", foto: "img/dino_zoff.jpg" },
  { nombre: "Diogo Jota", foto: "img/diogo_jota.jpg" },
  { nombre: "Domenico Berardi", foto: "img/domenico_berardi.jpg" },
  { nombre: "Douglas Luiz", foto: "img/douglas_luiz.jpg" },
  { nombre: "Dries Mertens", foto: "img/dries_mertens.jpg" },
  { nombre: "Dušan Vlahović", foto: "img/dušan_vlahović.jpg" },
  { nombre: "Dunga", foto: "img/dunga.jpg" },
  { nombre: "Éder Militão", foto: "img/eder_militao.jpg" },
  { nombre: "Eden Hazard", foto: "img/eden_hazard.jpg" },
  { nombre: "Eden Višća", foto: "img/eden_višca.jpg" },
  { nombre: "Ederson", foto: "img/ederson.jpg" },
  { nombre: "Edinson Cavani", foto: "img/edinson_cavani.jpg" },
  { nombre: "Eduardo Camavinga", foto: "img/eduardo_camavinga.jpg" },
  { nombre: "Eduardo Darias", foto: "img/eduardo_darias.jpg" },
  { nombre: "Eduardo Vargas", foto: "img/eduardo_vargas.jpg" },
  { nombre: "Edouard Mendy", foto: "img/edouard_mendy.jpg" },
  { nombre: "Edwin van der Sar", foto: "img/edwin_van_der_sar.jpg" },
  { nombre: "El Hadji Diouf", foto: "img/el_hadji_diouf.jpg" },
  { nombre: "Emanuel Gularte", foto: "img/emanuel_gularte.jpg" },
  { nombre: "Emiliano 'Dibu' Martínez", foto: "img/emiliano_dibu_martínez.jpg" },
  { nombre: "Emiliano Velázquez", foto: "img/emiliano_velázquez.jpg" },
  { nombre: "Emilio Butragueño", foto: "img/emilio_butragueño.jpg" },
  { nombre: "Emre Can", foto: "img/emre_can.jpg" },
  { nombre: "Emerson", foto: "img/emerson.jpg" },
  { nombre: "Emmanuel Adebayor", foto: "img/emmanuel_adebayor.jpg" },
  { nombre: "Enner Valencia", foto: "img/enner_valencia.jpg" },
  { nombre: "Endrick", foto: "img/endrick.jpg" },
  { nombre: "Enzo Fernández", foto: "img/enzo_fernández.jpg" },
  { nombre: "Enzo Francescoli", foto: "img/enzo_francescoli.jpg" },
  { nombre: "Enzo Pérez", foto: "img/enzo_pérez.jpg" },
  { nombre: "Eric Cantona", foto: "img/eric_cantona.jpg" },
  { nombre: "Erling Haaland", foto: "img/erling_haaland.jpg" },
  { nombre: "Essam El Hadary", foto: "img/essam_el_hadary.jpg" },
  { nombre: "Esteban Cambiasso", foto: "img/esteban_cambiasso.jpg" },
  { nombre: "Eusébio", foto: "img/eusebio.jpg" },
  { nombre: "Éver Banega", foto: "img/ever_banega.jpg" },
  { nombre: "Ezequiel Lavezzi", foto: "img/ezequiel_lavezzi.jpg" },
  { nombre: "Fabio Capello", foto: "img/fabio_capello.jpg" },
  { nombre: "Fabio Cannavaro", foto: "img/fabio_cannavaro.jpg" },
  { nombre: "Fabio Grosso", foto: "img/fabio_grosso.jpg" },
  { nombre: "Fabinho", foto: "img/fabinho.jpg" },
  { nombre: "Facundo Buonanotte", foto: "img/facundo_buonanotte.jpg" },
  { nombre: "Facundo Machado", foto: "img/facundo_machado.jpg" },
  { nombre: "Facundo Pellistri", foto: "img/facundo_pellistri.jpg" },
  { nombre: "Faustino Asprilla", foto: "img/faustino_asprilla.jpg" },
  { nombre: "Federico Bernardeschi", foto: "img/federico_bernardeschi.jpg" },
  { nombre: "Federico Chiesa", foto: "img/federico_chiesa.jpg" },
  { nombre: "Federico Valverde", foto: "img/federico_valverde.jpg" },
  { nombre: "Felipe Carballo", foto: "img/felipe_carballo.jpg" },
  { nombre: "Felipe Carvalho", foto: "img/felipe_carvalho.jpg" },
  { nombre: "Felipe Melo", foto: "img/felipe_melo.jpg" },
  { nombre: "Ferenc Puskás", foto: "img/ferenc_puskas.jpg" },
  { nombre: "Fernando Hierro", foto: "img/fernando_hierro.jpg" },
  { nombre: "Fernando Llorente", foto: "img/fernando_llorente.jpg" },
  { nombre: "Fernando Morena", foto: "img/fernando_morena.jpg" },
  { nombre: "Fernando Muslera", foto: "img/fernando_muslera.jpg" },
  { nombre: "Fernando Redondo", foto: "img/fernando_redondo.jpg" },
  { nombre: "Fernando Torres", foto: "img/fernando_torres.jpg" },
  { nombre: "Filippo Inzaghi", foto: "img/filippo_inzaghi.jpg" },
  { nombre: "Florian Neuhaus", foto: "img/florian_neuhaus.jpg" },
  { nombre: "Franck Kessié", foto: "img/franck_kessie.jpg" },
  { nombre: "Franck Ribéry", foto: "img/franck_ribéry.jpg" },
  { nombre: "Franco Baresi", foto: "img/franco_baresi.jpg" },
  { nombre: "Franco Fagúndez", foto: "img/franco_fagúndez.jpg" },
  { nombre: "Franco Mastantuono", foto: "img/franco_mastantuono.jpg" },
  { nombre: "Francesco Acerbi", foto: "img/francesco_acerbi.jpg" },
  { nombre: "Francesco Totti", foto: "img/francesco_totti.jpg" },
  { nombre: "Franz Beckenbauer", foto: "img/franz_beckenbauer.jpg" },
  { nombre: "Fred", foto: "img/fred.jpg" },
  { nombre: "Frédéric Kanouté", foto: "img/frédéric_kanouté.jpg" },
  { nombre: "Gabriel Jesus", foto: "img/gabriel_jesus.jpg" },
  { nombre: "Gabriel Magalhães", foto: "img/gabriel_magalhães.jpg" },
  { nombre: "Gabriel Martinelli", foto: "img/gabriel_martinelli.jpg" },
  { nombre: "Gabriel Batistuta", foto: "img/gabriel_batistuta.jpg" },
  { nombre: "Gabriel Heinze", foto: "img/gabriel_heinze.jpg" },
  { nombre: "Gabriel Jesus", foto: "img/gabriel_jesus.jpg" },
  { nombre: "Gabriel Martinelli", foto: "img/gabriel_martinelli.jpg" },
  { nombre: "Gabriel Valdano", foto: "img/gabriel_valdano.jpg" },
  { nombre: "Gareth Bale", foto: "img/gareth_bale.jpg" },
  { nombre: "Garrincha", foto: "img/garrincha.jpg" },
  { nombre: "Gary Medel", foto: "img/gary_medel.jpg" },
  { nombre: "Gastón Silva", foto: "img/gastón_silva.jpg" },
  { nombre: "Gaizka Mendieta", foto: "img/gaizka_mendieta.jpg" },
  { nombre: "Gennaro Gattuso", foto: "img/gennaro_gattuso.jpg" },
  { nombre: "George Best", foto: "img/george_best.jpg" },
  { nombre: "George Weah", foto: "img/george_weah.jpg" },
  { nombre: "Georgi Asparuhov", foto: "img/georgi_asparuhov.jpg" },
  { nombre: "Gerard Deulofeu", foto: "img/gerard_deulofeu.jpg" },
  { nombre: "Gerard Moreno", foto: "img/gerard_moreno.jpg" },
  { nombre: "Gerard Piqué", foto: "img/gerard_piqué.jpg" },
  { nombre: "Geremi Njitap", foto: "img/geremi_njitap.jpg" },
  { nombre: "Gerson", foto: "img/gerson.jpg" },
  { nombre: "Gheorghe Hagi", foto: "img/gheorghe_hagi.jpg" },
  { nombre: "Gianluca Scamacca", foto: "img/gianluca_scamacca.jpg" },
  { nombre: "Gianluca Vialli", foto: "img/gianluca_vialli.jpg" },
  { nombre: "Gianluca Zambrotta", foto: "img/gianluca_zambrotta.jpg" },
  { nombre: "Gianluigi Buffon", foto: "img/gianluigi_buffon.jpg" },
  { nombre: "Gianluigi Donnarumma", foto: "img/gianluigi_donnarumma.jpg" },
  { nombre: "Giorgian De Arrascaeta", foto: "img/giorgian_de_arrascaeta.jpg" },
  { nombre: "Giorgio Chiellini", foto: "img/giorgio_chiellini.jpg" },
  { nombre: "Giovani dos Santos", foto: "img/giovani_dos_santos.jpg" },
  { nombre: "Gonzalo Carneiro", foto: "img/gonzalo_carneiro.jpg" },
  { nombre: "Gonzalo Higuaín", foto: "img/gonzalo_higuain.jpg" },
  { nombre: "Gonzalo Petit", foto: "img/gonzalo_petit.jpg" },
  { nombre: "Gonçalo Ramos", foto: "img/gonçalo_ramos.jpg" },
  { nombre: "Granit Xhaka", foto: "img/granit_xhaka.jpg" },
  { nombre: "Gunnar Nordahl", foto: "img/gunnar_nordahl.jpg" },
  { nombre: "Gustavo Gómez", foto: "img/gustavo_gómez.jpg" },
  { nombre: "Guti", foto: "img/guti.jpg" },
  { nombre: "Hakim Ziyech", foto: "img/hakim_ziyech.jpg" },
  { nombre: "Harry Kane", foto: "img/harry_kane.jpg" },
  { nombre: "Harry Maguire", foto: "img/harry_maguire.jpg" },
  { nombre: "Harry Souttar", foto: "img/harry_souttar.jpg" },
  { nombre: "Haris Seferović", foto: "img/haris_seferović.jpg" },
  { nombre: "Héctor Chumpitaz", foto: "img/hector_chumpitaz.jpg" },
  { nombre: "Héctor Herrera", foto: "img/hector_herrera.jpg" },
  { nombre: "Héctor Scarone", foto: "img/hector_scarone.jpg" },
  { nombre: "Hee-chan Hwang", foto: "img/hee_chan_hwang.jpg" },
  { nombre: "Helenio Herrera", foto: "img/helenio_herrera.jpg" },
  { nombre: "Henrik Larsson", foto: "img/henrik_larsson.jpg" },
  { nombre: "Henrikh Mkhitaryan", foto: "img/henrikh_mkhitaryan.jpg" },
  { nombre: "Hernán Crespo", foto: "img/hernán_crespo.jpg" },
  { nombre: "Hernanes", foto: "img/hernanes.jpg" },
  { nombre: "Heung-min Son", foto: "img/heung_min_son.jpg" },
  { nombre: "Hidetoshi Nakata", foto: "img/hidetoshi_nakata.jpg" },
  { nombre: "Hristo Stoichkov", foto: "img/hristo_stoichkov.jpg" },
  { nombre: "Hugo Lloris", foto: "img/hugo_lloris.jpg" },
  { nombre: "Hugo Sánchez", foto: "img/hugo_sánchez.jpg" },
  { nombre: "Iago Aspas", foto: "img/iago_aspas.jpg" },
  { nombre: "Ignacio Lores", foto: "img/ignacio_lores.jpg" },
  { nombre: "Ignacio Sosa", foto: "img/ignacio_sosa.jpg" },
  { nombre: "Iker Casillas", foto: "img/iker_casillas.jpg" },
  { nombre: "Ilkay Gündogan", foto: "img/ilkay_gundogan.jpg" },
  { nombre: "Illarramendi", foto: "img/illarramendi.jpg" },
  { nombre: "Iñaki Williams", foto: "img/iñaki_williams.jpg" },
  { nombre: "Irving Lozano", foto: "img/irving_lozano.jpg" },
  { nombre: "Isco", foto: "img/isco.jpg" },
  { nombre: "Islam Slimani", foto: "img/islam_slimani.jpg" },
  { nombre: "Ismaël Bennacer", foto: "img/ismael_bennacer.jpg" },
  { nombre: "Iván Alonso", foto: "img/ivan_alonso.jpg" },
  { nombre: "Iván Hurtado", foto: "img/ivan_hurtado.jpg" },
  { nombre: "Iván Ramiro Córdoba", foto: "img/ivan_ramiro_córdoba.jpg" },
  { nombre: "Iván Rakitić", foto: "img/ivan_rakitic.jpg" },
  { nombre: "Iván Zamorano", foto: "img/ivan_zamorano.jpg" },
  { nombre: "Jack Grealish", foto: "img/jack_grealish.jpg" },
  { nombre: "Jadon Sancho", foto: "img/jadon_sancho.jpg" },
  { nombre: "Jae-sung Lee", foto: "img/jae_sung_lee.jpg" },
  { nombre: "Jairzinho", foto: "img/jairzinho.jpg" },
  { nombre: "James Maddison", foto: "img/james_maddison.jpg" },
  { nombre: "James Rodríguez", foto: "img/james_rodríguez.jpg" },
  { nombre: "Jan Koller", foto: "img/jan_koller.jpg" },
  { nombre: "Jan Vertonghen", foto: "img/jan_vertonghen.jpg" },
  { nombre: "Javier Cabrera", foto: "img/javier_cabrera.jpg" },
  { nombre: "Javier Hernández 'Chicharito'", foto: "img/javier_hernandez_chicharito.jpg" },
  { nombre: "Javier Mascherano", foto: "img/javier_mascherano.jpg" },
  { nombre: "Javier Zanetti", foto: "img/javier_zanetti.jpg" },
  { nombre: "Jay-Jay Okocha", foto: "img/jay_jay_okocha.jpg" },
  { nombre: "Jefferson Farfán", foto: "img/jefferson_farfán.jpg" },
  { nombre: "Jeremías Recoba", foto: "img/jeremías_recoba.jpg" },
  { nombre: "Jerome Boateng", foto: "img/jerome_boateng.jpg" },
  { nombre: "Jesús Navas", foto: "img/jesús_navas.jpg" },
  { nombre: "Jesús Trindade", foto: "img/jesús_trindade.jpg" },
  { nombre: "Joakim Maehle", foto: "img/joakim_maehle.jpg" },
  { nombre: "João Cancelo", foto: "img/joao_cancelo.jpg" },
  { nombre: "João Félix", foto: "img/joao_felix.jpg" },
  { nombre: "João Gomes", foto: "img/joao_gomes.jpg" },
  { nombre: "João Moutinho", foto: "img/joao_moutinho.jpg" },
  { nombre: "Johan Cruyff", foto: "img/johan_cruyff.jpg" },
  { nombre: "Joe Cole", foto: "img/joe_cole.jpg" },
  { nombre: "Jonathan David", foto: "img/jonathan_david.jpg" },
  { nombre: "Jonathan Tah", foto: "img/jonathan_tah.jpg" },
  { nombre: "Jonathan Rodríguez", foto: "img/jonathan_rodríguez.jpg" },
  { nombre: "Jordi Alba", foto: "img/jordi_alba.jpg" },
  { nombre: "Jordan Henderson", foto: "img/jordan_henderson.jpg" },
  { nombre: "Jorge Campos", foto: "img/jorge_campos.jpg" },
  { nombre: "Jorge Valdano", foto: "img/jorge_valdano.jpg" },
  { nombre: "Jorginho", foto: "img/jorginho.jpg" },
  { nombre: "José Antonio Reyes", foto: "img/jose_antonio_reyes.jpg" },
  { nombre: "José Luis Chilavert", foto: "img/jose_luis_chilavert.jpg" },
  { nombre: "José María Giménez", foto: "img/jose_maría_gimenez.jpg" },
  { nombre: "José Mourinho", foto: "img/jose_mourinho.jpg" },
  { nombre: "José Saturnino Cardozo", foto: "img/jose_saturnino_cardozo.jpg" },
  { nombre: "Josef Martínez", foto: "img/josef_martínez.jpg" },
  { nombre: "Joshua Kimmich", foto: "img/joshua_kimmich.jpg" },
  { nombre: "Joško Gvardiol", foto: "img/josko_gvardiol.jpg" },
  { nombre: "Juan Arango", foto: "img/juan_arango.jpg" },
  { nombre: "Juan Guillermo Cuadrado", foto: "img/juan_guillermo_cuadrado.jpg" },
  { nombre: "Juan Mata", foto: "img/juan_mata.jpg" },
  { nombre: "Juan Román Riquelme", foto: "img/juan_román_riquelme.jpg" },
  { nombre: "Jude Bellingham", foto: "img/jude_bellingham.jpg" },
  { nombre: "Julen Guerrero", foto: "img/julen_guerrero.jpg" },
  { nombre: "Julio Cesar", foto: "img/julio_cesar.jpg" },
  { nombre: "Juninho Pernambucano", foto: "img/juninho_pernambucano.jpg" },
  { nombre: "Jürgen Klopp", foto: "img/jürgen_klopp.jpg" },
  { nombre: "Kai Havertz", foto: "img/kai_havertz.jpg" },
  { nombre: "Kaká", foto: "img/kaka.jpg" },
  { nombre: "Kalidou Koulibaly", foto: "img/kalidou_koulibaly.jpg" },
  { nombre: "Kalusha Bwalya", foto: "img/kalusha_bwalya.jpg" },
  { nombre: "Kalvin Phillips", foto: "img/kalvin_phillips.jpg" },
  { nombre: "Karim Benzema", foto: "img/karim_benzema.jpg" },
  { nombre: "Kasper Schmeichel", foto: "img/kasper_schmeichel.jpg" },
  { nombre: "Keisuke Honda", foto: "img/keisuke_honda.jpg" },
  { nombre: "Kevin De Bruyne", foto: "img/kevin_de_bruyne.jpg" },
  { nombre: "Kevin Strootman", foto: "img/kevin_strootman.jpg" },
  { nombre: "Keylor Navas", foto: "img/keylor_navas.jpg" },
  { nombre: "Khvicha Kvaratskhelia", foto: "img/khvicha_kvaratskhelia.jpg" },
  { nombre: "Kieran Tierney", foto: "img/kieran_tierney.jpg" },
  { nombre: "Kieran Trippier", foto: "img/kieran_trippier.jpg" },
  { nombre: "Kim Min-jae", foto: "img/kim_min_jae.jpg" },
  { nombre: "Kingsley Coman", foto: "img/kingsley_coman.jpg" },
  { nombre: "Koke", foto: "img/koke.jpg" },
  { nombre: "Konrad Laimer", foto: "img/konrad_laimer.jpg" },
  { nombre: "Kyle Walker", foto: "img/kyle_walker.jpg" },
  { nombre: "Kylian Mbappé", foto: "img/kylian_mbappe.jpg" },
  { nombre: "Lamine Yamal", foto: "img/lamine_yamal.jpg" },
  { nombre: "Landon Donovan", foto: "img/landon_donovan.jpg" },
  { nombre: "Lautaro Martínez", foto: "img/lautaro_martínez.jpg" },
  { nombre: "Laurent Blanc", foto: "img/laurent_blanc.jpg" },
  { nombre: "Lauren Etamé Mayer", foto: "img/lauren_etame_mayer.jpg" },
  { nombre: "Leandro Paredes", foto: "img/leandro_paredes.jpg" },
  { nombre: "Lee Kang-in", foto: "img/lee_kang_in.jpg" },
  { nombre: "Leonardo Bonucci", foto: "img/leonardo_bonucci.jpg" },
  { nombre: "Leonardo Fernández", foto: "img/leonardo_fernández.jpg" },
  { nombre: "Leon Goretzka", foto: "img/leon_goretzka.jpg" },
  { nombre: "Leroy Sané", foto: "img/leroy_sane.jpg" },
  { nombre: "Lev Yashin", foto: "img/lev_yashin.jpg" },
  { nombre: "Lilian Thuram", foto: "img/lilian_thuram.jpg" },
  { nombre: "Lionel Messi", foto: "img/lionel_messi.jpg" },
  { nombre: "Lionel Scaloni", foto: "img/lionel_scaloni.jpg" },
  { nombre: "Lisandro Martínez", foto: "img/lisandro_martínez.jpg" },
  { nombre: "Luca Toni", foto: "img/luca_toni.jpg" },
  { nombre: "Lucas Biglia", foto: "img/lucas_biglia.jpg" },
  { nombre: "Lucas Hernández", foto: "img/lucas_hernández.jpg" },
  { nombre: "Lucas Moura", foto: "img/lucas_moura.jpg" },
  { nombre: "Lucas Paquetá", foto: "img/lucas_paqueta.jpg" },
  { nombre: "Lucas Torreira", foto: "img/lucas_torreira.jpg" },
  { nombre: "Lucio", foto: "img/lucio.jpg" },
  { nombre: "Luis Artime", foto: "img/luis_artime.jpg" },
  { nombre: "Luis Díaz", foto: "img/luis_díaz.jpg" },
  { nombre: "Luis Enrique", foto: "img/luis_enrique.jpg" },
  { nombre: "Luis Figo", foto: "img/luis_figo.jpg" },
  { nombre: "Luis Suárez", foto: "img/luis_suárez.jpg" },
  { nombre: "Luka Jović", foto: "img/luka_jović.jpg" },
  { nombre: "Luka Modrić", foto: "img/luka_modríc.jpg" },
  { nombre: "Luke Shaw", foto: "img/luke_shaw.jpg" },
  { nombre: "Maicon", foto: "img/maicon.jpg" },
  { nombre: "Mahmoud Trézéguet", foto: "img/mahmoud_trézéguet.jpg" },
  { nombre: "Manuel Locatelli", foto: "img/manuel_locatelli.jpg" },
  { nombre: "Manuel Ugarte", foto: "img/manuel_ugarte.jpg" },
  { nombre: "Manuel Neuer", foto: "img/manuel_neuer.jpg" },
  { nombre: "Marc-André ter Stegen", foto: "img/marc_andré_ter_stegen.jpg" },
  { nombre: "Marcel Desailly", foto: "img/marcel_desailly.jpg" },
  { nombre: "Marcel Sabitzer", foto: "img/marcel_sabitzer.jpg" },
  { nombre: "Marcelo Brozović", foto: "img/marcelo_brozović.jpg" },
  { nombre: "Marcelo Martins Moreno", foto: "img/marcelo_martins_moreno.jpg" },
  { nombre: "Marcelo Salas", foto: "img/marcelo_salas.jpg" },
  { nombre: "Marcello Lippi", foto: "img/marcello_lippi.jpg" },
  { nombre: "Marco Asensio", foto: "img/marco_asensio.jpg" },
  { nombre: "Marco Materazzi", foto: "img/marco_materazzi.jpg" },
  { nombre: "Marco Reus", foto: "img/marco_reus.jpg" },
  { nombre: "Marco van Basten", foto: "img/marco_van_basten.jpg" },
  { nombre: "Marco Verratti", foto: "img/marco_verratti.jpg" },
  { nombre: "Marcos Rojo", foto: "img/marcos_rojo.jpg" },
  { nombre: "Marcus Rashford", foto: "img/marcus_rashford.jpg" },
  { nombre: "Marek Hamšík", foto: "img/marek_hamšík.jpg" },
  { nombre: "Mario Balotelli", foto: "img/mario_balotelli.jpg" },
  { nombre: "Mario Gómez", foto: "img/mario_gómez.jpg" },
  { nombre: "Mario Kempes", foto: "img/mario_kempes.jpg" },
  { nombre: "Mario Mandžukić", foto: "img/mario_mandžukić.jpg" },
  { nombre: "Mark Schwarzer", foto: "img/mark_schwarzer.jpg" },
  { nombre: "Marko Arnautović", foto: "img/marko_arnautović.jpg" },
  { nombre: "Marquinhos", foto: "img/marquinhos.jpg" },
  { nombre: "Martín Cáceres", foto: "img/martín_cáceres.jpg" },
  { nombre: "Martin Braithwaite", foto: "img/martin_braithwaite.jpg" },
  { nombre: "Martin Dúbravka", foto: "img/martin_dúbravka.jpg" },
  { nombre: "Mason Mount", foto: "img/mason_mount.jpg" },
  { nombre: "Massimo Ambrosini", foto: "img/massimo_ambrosini.jpg" },
  { nombre: "Mathew Ryan", foto: "img/mathew_ryan.jpg" },
  { nombre: "Matías Arezo", foto: "img/matías_arezo.jpg" },
  { nombre: "Matías Fernández", foto: "img/matías_fernández.jpg" },
  { nombre: "Matías Soulé", foto: "img/matías_soulé.jpg" },
  { nombre: "Matías Viña", foto: "img/matías_viña.jpg" },
  { nombre: "Mats Hummels", foto: "img/mats_hummels.jpg" },
  { nombre: "Mattia Zaccagni", foto: "img/mattia_zaccagni.jpg" },
  { nombre: "Matteo Darmian", foto: "img/matteo_darmian.jpg" },
  { nombre: "Matteo Politano", foto: "img/matteo_politano.jpg" },
  { nombre: "Mauro Camoranesi", foto: "img/mauro_camoranesi.jpg" },
  { nombre: "Mauro Icardi", foto: "img/mauro_icardi.jpg" },
  { nombre: "Maxi Rodríguez", foto: "img/maxi_rodríguez.jpg" },
  { nombre: "Maximiliano Olivera", foto: "img/maximiliano_olivera.jpg" },
  { nombre: "Maximiliano Silvera", foto: "img/maximiliano_silvera.jpg" },
  { nombre: "Maya Yoshida", foto: "img/maya_yoshida.jpg" },
  { nombre: "Mehdi Benatia", foto: "img/mehdi_benatia.jpg" },
  { nombre: "Memphis Depay", foto: "img/memphis_depay.jpg" },
  { nombre: "Mesut Özil", foto: "img/mesut_ozil.jpg" },
  { nombre: "Michel", foto: "img/michel.jpg" },
  { nombre: "Michel Platini", foto: "img/michel_platini.jpg" },
  { nombre: "Michael Essien", foto: "img/michael_essien.jpg" },
  { nombre: "Michael Laudrup", foto: "img/michael_laudrup.jpg" },
  { nombre: "Michael Owen", foto: "img/michael_owen.jpg" },
  { nombre: "Michy Batshuayi", foto: "img/michy_batshuayi.jpg" },
  { nombre: "Mido (Ahmed Hossam)", foto: "img/mido_ahmed_hossam.jpg" },
  { nombre: "Miguel Almirón", foto: "img/miguel_almirón.jpg" },
  { nombre: "Mikel Oyarzabal", foto: "img/mikel_oyarzabal.jpg" },
  { nombre: "Miralem Pjanić", foto: "img/miralem_pjaníc.jpg" },
  { nombre: "Miroslav Klose", foto: "img/miroslav_klose.jpg" },
  { nombre: "Mohamed Aboutrika", foto: "img/mohamed_aboutrika.jpg" },
  { nombre: "Mohamed Elneny", foto: "img/mohamed_elneny.jpg" },
  { nombre: "Mohamed Salah", foto: "img/mohamed_salah.jpg" },
  { nombre: "Mohammed Kudus", foto: "img/mohammed_kudus.jpg" },
  { nombre: "Moisés Caicedo", foto: "img/moisés_caicedo.jpg" },
  { nombre: "Mustapha Hadji", foto: "img/mustapha_hadji.jpg" },
  { nombre: "N'Golo Kanté", foto: "img/ngolo_kante.jpg" },
  { nombre: "Nacho Fernández", foto: "img/nacho_fernández.jpg" },
  { nombre: "Nani", foto: "img/nani.jpg" },
  { nombre: "Nathan Aké", foto: "img/nathan_ake.jpg" },
  { nombre: "Nemanja Matić", foto: "img/nemanja_matíc.jpg" },
  { nombre: "Neymar Jr.", foto: "img/neymar_jr.jpg" },
  { nombre: "Nico López", foto: "img/nico_lopez.jpg" },
  { nombre: "Nico Williams", foto: "img/nico_williams.jpg" },
  { nombre: "Nicolo Barella", foto: "img/nicolo_barella.jpg" },
  { nombre: "Nicolo Zaniolo", foto: "img/nicolo_zaniolo.jpg" },
  { nombre: "Nicolás de la Cruz", foto: "img/nicolas_de_la_cruz.jpg" },
  { nombre: "Nicolás Lodeiro", foto: "img/nicolás_lodeiro.jpg" },
  { nombre: "Nicolás Otamendi", foto: "img/nicolás_otamendi.jpg" },
  { nombre: "Nicolás Paz", foto: "img/nicolás_paz.jpg" },
  { nombre: "Niklas Süle", foto: "img/niklas_sule.jpg" },
  { nombre: "Nolberto Solano", foto: "img/nolberto_solano.jpg" },
  { nombre: "Nwankwo Kanu", foto: "img/nwankwo_kanu.jpg" },
  { nombre: "Obafemi Martins", foto: "img/obafemi_martins.jpg" },
  { nombre: "Obdulio Varela", foto: "img/obdulio_varela.jpg" },
  { nombre: "Odion Ighalo", foto: "img/odion_ighalo.jpg" },
  { nombre: "Omar Sívori", foto: "img/omar_sívor.jpg" },
  { nombre: "Ousmane Dembélé", foto: "img/ousmane_dembele.jpg" },
  { nombre: "Oswaldo Sánchez", foto: "img/oswaldo_sánchez.jpg" },
  { nombre: "Óscar Washington Tabárez", foto: "img/oscar_washington_tabárez.jpg" },
  { nombre: "Pablo Aimar", foto: "img/pablo_aimar.jpg" },
  { nombre: "Pablo Sarabia", foto: "img/pablo_sarabia.jpg" },
  { nombre: "Paolo Calione", foto: "img/paolo_calione.jpg" },
  { nombre: "Paolo Guerrero", foto: "img/paolo_guerrero.jpg" },
  { nombre: "Paolo Maldini", foto: "img/paolo_maldini.jpg" },
  { nombre: "Papu Gómez", foto: "img/papu_gómez.jpg" },
  { nombre: "Patrick Kluivert", foto: "img/patrick_kluivert.jpg" },
  { nombre: "Patrick Vieira", foto: "img/patrick_vieira.jpg" },
  { nombre: "Pau Torres", foto: "img/pau_torres.jpg" },
  { nombre: "Paul Pogba", foto: "img/paul_pogba.jpg" },
  { nombre: "Paulo Futre", foto: "img/paulo_futre.jpg" },
  { nombre: "Pavel Nedvěd", foto: "img/pavel_nedved.jpg" },
  { nombre: "Pedro Milans", foto: "img/pedro_milans.jpg" },
  { nombre: "Pedri", foto: "img/pedri.jpg" },
  { nombre: "Pelé", foto: "img/pele.jpg" },
  { nombre: "Pepe", foto: "img/pepe.jpg" },
  { nombre: "Pepe Reina", foto: "img/pepe_reina.jpg" },
  { nombre: "Pep Guardiola", foto: "img/pep_guardiola.jpg" },
  { nombre: "Petr Čech", foto: "img/petr_cech.jpg" },
  { nombre: "Phil Foden", foto: "img/phil_foden.jpg" },
  { nombre: "Philipp Lahm", foto: "img/philipp_lahm.jpg" },
  { nombre: "Pierre-Emerick Aubameyang", foto: "img/pierre_emerick_aubameyang.jpg" },
  { nombre: "Pierre-Emile Højbjerg", foto: "img/pierre_emile_hojbjerg.jpg" },
  { nombre: "Pippo Inzaghi", foto: "img/pippo_inzaghi.jpg" },
  { nombre: "Raheem Sterling", foto: "img/raheem_sterling.jpg" },
  { nombre: "Rafael Guerreiro", foto: "img/rafael_guerreiro.jpg" },
  { nombre: "Rafael van der Vaart", foto: "img/rafael_van_der_vaart.jpg" },
  { nombre: "Rafa Márquez", foto: "img/rafa_márquez.jpg" },
  { nombre: "Raphinha", foto: "img/raphinha.jpg" },
  { nombre: "Raphaël Varane", foto: "img/raphaël_varane.jpg" },
  { nombre: "Raúl Albiol", foto: "img/raúl_albiol.jpg" },
  { nombre: "Raúl González", foto: "img/raúl_gonzález.jpg" },
  { nombre: "Raúl Jiménez", foto: "img/raúl_jiménez.jpg" },
  { nombre: "Renan Lodi", foto: "img/renan_lodi.jpg" },
  { nombre: "René Higuita", foto: "img/rene_higuita.jpg" },
  { nombre: "Ricardo Bochini", foto: "img/ricardo_bochini.jpg" },
  { nombre: "Ricardo Kaká", foto: "img/ricardo_kaka.jpg" },
  { nombre: "Ricardo Quaresma", foto: "img/ricardo_quaresma.jpg" },
  { nombre: "Richarlison", foto: "img/richarlison.jpg" },
  { nombre: "Rigobert Song", foto: "img/rigobert_song.jpg" },
  { nombre: "Rinus Michels", foto: "img/rinus_michels.jpg" },
  { nombre: "Rio Ferdinand", foto: "img/rio_ferdinand.jpg" },
  { nombre: "Rivaldo", foto: "img/rivaldo.jpg" },
  { nombre: "Rivelino", foto: "img/rivelino.jpg" },
  { nombre: "Riyad Bensebaini", foto: "img/riyad_bensebaini.jpg" },
  { nombre: "Riyad Mahrez", foto: "img/riyad_mahrez.jpg" },
  { nombre: "Roberto Baggio", foto: "img/roberto_baggio.jpg" },
  { nombre: "Roberto Ayala", foto: "img/roberto_ayala.jpg" },
  { nombre: "Roberto Carlos", foto: "img/roberto_carlos.jpg" },
  { nombre: "Roberto Mancini", foto: "img/roberto_mancini.jpg" },
  { nombre: "Robert Lewandowski", foto: "img/robert_lewandowski.jpg" },
  { nombre: "Rodri Hernández", foto: "img/rodri_hernández.jpg" },
  { nombre: "Rodrigo Bentancur", foto: "img/rodrigo_bentancur.jpg" },
  { nombre: "Rodrigo De Paul", foto: "img/rodrigo_de_paul.jpg" },
  { nombre: "Rodrygo Goes", foto: "img/rodrygo_goes.jpg" },
  { nombre: "Roger Milla", foto: "img/roger_milla.jpg" },
  { nombre: "Romário", foto: "img/romario.jpg" },
  { nombre: "Romelu Lukaku", foto: "img/romelu_lukaku.jpg" },
  { nombre: "Ronald Araújo", foto: "img/ronald_araújo.jpg" },
  { nombre: "Ronaldinho", foto: "img/ronaldinho.jpg" },
  { nombre: "Ronaldo Nazario", foto: "img/ronaldo_nazario.jpg" },
  { nombre: "Roque Santa Cruz", foto: "img/roque_santa_cruz.jpg" },
  { nombre: "Rubén Baraja", foto: "img/ruben_baraja.jpg" },
  { nombre: "Rubén Sosa", foto: "img/ruben_sosa.jpg" },
  { nombre: "Ruud Gullit", foto: "img/ruud_gullit.jpg" },
  { nombre: "Ruud van Nistelrooy", foto: "img/ruud_van_nistelrooy.jpg" },
  { nombre: "Rúben Dias", foto: "img/ruben_dias.jpg" },
  { nombre: "Rúben Neves", foto: "img/ruben_neves.jpg" },
  { nombre: "Sadio Mané", foto: "img/sadio_mane.jpg" },
  { nombre: "Saeed Al-Owairan", foto: "img/saeed_al_owairan.jpg" },
  { nombre: "Salomón Rondón", foto: "img/salomón_rondón.jpg" },
  { nombre: "Salvatore Schillaci", foto: "img/salvatore_schillaci.jpg" },
  { nombre: "Salvatore Sirigu", foto: "img/salvatore_sirigu.jpg" },
  { nombre: "Samuel Eto’o", foto: "img/samuel_etoo.jpg" },
  { nombre: "Samuel Kuffour", foto: "img/samuel_kuffour.jpg" },
  { nombre: "Samuel Umtiti", foto: "img/samuel_umtiti.jpg" },
  { nombre: "Sandro Tonali", foto: "img/sandro_tonali.jpg" },
  { nombre: "Santi Cazorla", foto: "img/santi_cazorla.jpg" },
  { nombre: "Saúl Ñíguez", foto: "img/saúl_ñíguez.jpg" },
  { nombre: "Sebastián Abreu", foto: "img/sebastián_abreu.jpg" },
  { nombre: "Sebastián Coates", foto: "img/sebastián_coates.jpg" },
  { nombre: "Sergio Agüero", foto: "img/sergio_agüero.jpg" },
  { nombre: "Sergio Busquets", foto: "img/sergio_busquets.jpg" },
  { nombre: "Sergio Canales", foto: "img/sergio_canales.jpg" },
  { nombre: "Sergio Ramos", foto: "img/sergio_ramos.jpg" },
  { nombre: "Sergio Rochet", foto: "img/sergio_rochet.jpg" },
  { nombre: "Serge Gnabry", foto: "img/serge_gnabry.jpg" },
  { nombre: "Sergej Milinković-Savić", foto: "img/sergej_milinkovíc_savic.jpg" },
  { nombre: "Shabani Nonda", foto: "img/shabani_nonda.jpg" },
  { nombre: "Shinji Kagawa", foto: "img/shinji_kagawa.jpg" },
  { nombre: "Shunsuke Nakamura", foto: "img/shunsuke_nakamura.jpg" },
  { nombre: "Siniša Mihajlović", foto: "img/siniša_mihajlović.jpg" },
  { nombre: "Sir Alex Ferguson", foto: "img/sir_alex_ferguson.jpg" },
  { nombre: "Sócrates", foto: "img/sócrates.jpg" },
  { nombre: "Sofyan Amrabat", foto: "img/sofyan_amrabat.jpg" },
  { nombre: "Solomon Kalou", foto: "img/solomon_kalou.jpg" },
  { nombre: "Stefan de Vrij", foto: "img/stefan_de_vrij.jpg" },
  { nombre: "Steven Gerrard", foto: "img/steven_gerrard.jpg" },
  { nombre: "Takefusa Kubo", foto: "img/takefusa_kubo.jpg" },
  { nombre: "Takumi Minamino", foto: "img/takumi_minamino.jpg" },
  { nombre: "Tarik Sektioui", foto: "img/tarik_sektioui.jpg" },
  { nombre: "Teófilo Cubillas", foto: "img/teófilo_cubillas.jpg" },
  { nombre: "Theo Hernández", foto: "img/theo_hernández.jpg" },
  { nombre: "Thiago Alcántara", foto: "img/thiago_alcántara.jpg" },
  { nombre: "Thiago Almada", foto: "img/thiago_almada.jpg" },
  { nombre: "Thiago Silva", foto: "img/thiago_silva.jpg" },
  { nombre: "Thibaut Courtois", foto: "img/thibaut_courtois.jpg" },
  { nombre: "Thomas Müller", foto: "img/thomas_müller.jpg" },
  { nombre: "Thomas Partey", foto: "img/thomas_partey.jpg" },
  { nombre: "Thorgan Hazard", foto: "img/thorgan_hazard.jpg" },
  { nombre: "Thierry Henry", foto: "img/thierry_henry.jpg" },
  { nombre: "Tim Cahill", foto: "img/tim_cahill.jpg" },
  { nombre: "Tim Weah", foto: "img/tim_weah.jpg" },
  { nombre: "Timo Werner", foto: "img/timo_werner.jpg" },
  { nombre: "Toby Alderweireld", foto: "img/toby_alderweireld.jpg" },
  { nombre: "Tomás Rincón", foto: "img/tomás_rincón.jpg" },
  { nombre: "Toni Kroos", foto: "img/toni_kroos.jpg" },
  { nombre: "Tostão", foto: "img/tostao.jpg" },
  { nombre: "Trent Alexander-Arnold", foto: "img/trent_alexander_arnold.jpg" },
  { nombre: "Tyler Adams", foto: "img/tyler_adams.jpg" },
  { nombre: "Ubaldo Fillol", foto: "img/ubaldo_fillol.jpg" },
  { nombre: "Unai Simón", foto: "img/unai_simón.jpg" },
  { nombre: "Valentín Barco", foto: "img/valentín_barco.jpg" },
  { nombre: "Vicente del Bosque", foto: "img/vicente_del_bosque.jpg" },
  { nombre: "Victor Osimhen", foto: "img/victor_osimhen.jpg" },
  { nombre: "Víctor Moses", foto: "img/víctor_moses.jpg" },
  { nombre: "Vinícius Jr.", foto: "img/vinícius_jr.jpg" },
  { nombre: "Virgil van Dijk", foto: "img/virgil_van_dijk.jpg" },
  { nombre: "Vitinha", foto: "img/vitinha.jpg" },
  { nombre: "Walter Samuel", foto: "img/walter_samuel.jpg" },
  { nombre: "Walter Zenga", foto: "img/walter_zenga.jpg" },
  { nombre: "Wayne Rooney", foto: "img/wayne_rooney.jpg" },
  { nombre: "Wesley Sneijder", foto: "img/wesley_sneijder.jpg" },
  { nombre: "Weston McKennie", foto: "img/weston_mckennie.jpg" },
  { nombre: "Wilfred Ndidi", foto: "img/wilfred_ndidi.jpg" },
  { nombre: "William Carvalho", foto: "img/william_carvalho.jpg" },
  { nombre: "Winston Reid", foto: "img/winston_reid.jpg" },
  { nombre: "Wissam Ben Yedder", foto: "img/wissam_ben_yedder.jpg" },
  { nombre: "Xabi Alonso", foto: "img/xabi_alonso.jpg" },
  { nombre: "Xavi Hernández", foto: "img/xavi_hernández.jpg" },
  { nombre: "Xherdan Shaqiri", foto: "img/xherdan_shaqiri.jpg" },
  { nombre: "Yann Sommer", foto: "img/yann_sommer.jpg" },
  { nombre: "Yannick Carrasco", foto: "img/yannick_carrasco.jpg" },
  { nombre: "Yaya Touré", foto: "img/yaya_touré.jpg" },
  { nombre: "Yonatan Rodríguez", foto: "img/yonatan_rodríguez.jpg" },
  { nombre: "Youri Tielemans", foto: "img/youri_tielemans.jpg" },
  { nombre: "Youssef En-Nesyri", foto: "img/youssef_en_nesyri.jpg" },
  { nombre: "Zico", foto: "img/zico.jpg" },
  { nombre: "Zinedine Zidane", foto: "img/zinedine_zidane.jpg" },
  { nombre: "Zlatan Ibrahimović", foto: "img/zlatan_ibrahimović.jpg" },
  { nombre: "Zvonimir Boban", foto: "img/zvonimir_boban.jpg" },
];

// =========================================================
// INSERCIÓN AL FINAL DE famosos.js
// Esto permite que el servidor de Node.js pueda importar la lista
// =========================================================
module.exports = { famosos };

window.famosos = famosos;
